import React from 'react';
import type { Metadata } from 'next';
import {
  Montserrat,
  Plus_Jakarta_Sans,
  Roboto,
  Montserrat_Alternates,
  Outfit,
  Nunito,
  Urbanist,
} from 'next/font/google';
import './globals.scss';
import StoreProvider from './store-provider';

// Montserrat
const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--it-ff-heading',
});

// Plus Jakarta Sans
const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--it-ff-body',
});

// Roboto
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--it-ff-roboto',
});

// Montserrat Alternates
const montserratAlternates = Montserrat_Alternates({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--it-ff-montserrat',
});

// Outfit
const outfit = Outfit({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--it-ff-outfit',
});

// Nunito
const nunito = Nunito({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--it-ff-nunito',
});

// Urbanist
const urbanist = Urbanist({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--it-ff-urbanist',
});

export const metadata: Metadata = {
  title: 'Saasty - Sass Startup & Software Multipurpose Next Js Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${montserrat.variable} ${plusJakartaSans.variable} ${roboto.variable} ${montserratAlternates.variable} ${outfit.variable} ${nunito.variable} ${urbanist.variable}`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
